data:
  file_path_train_x: "/scratch/au2216/flowbench_fpo/sciml_fpo_project/dataset_generation/fpo/80_84-85_89/in_data.npz"
  file_path_train_y: "/scratch/au2216/flowbench_fpo/sciml_fpo_project/dataset_generation/fpo/80_84-85_89/out_data.npz"
  tmax: 9
  in_start: 0
  out_start: 0
  batch_size: 4

trainer:
  seed: 0
  epoch_per_timestep: 100
  delta_time_step: 1
  accelerator: gpu
  devices: 1
  log_every_n_steps: 10
  update_mode: pred

model:
  steps_in: 5
  steps_out: 1
  branch_net_layers: [512, 512, 512]
  trunk_net_layers: [256, 256, 256]
  modes: 128
  input_channels_loc: 2

callbacks:
  checkpoint: checkpoints
  filename: fpo-{epoch:02d}-{val_loss:.4f}
  monitor: val_r2_score_full
  mode: min
  save_top_k: 20
  every_n_epochs: 50
  save_last: true