callbacks:
  checkpoint:
    dirpath: /work/mech-ai/edherron/flowbench-sciml/checkpoints/ns/512_sdf_easy/
    every_n_epochs: 100
    filename: pod-deeponet-{epoch:02d}-{val_loss:.6f}
    mode: min
    monitor: val_loss_full
    save_top_k: -1
  dirpath: /work/mech-ai/edherron/flowbench-sciml/checkpoints/ns/512_sdf_easy/
  early_stopping:
    monitor: val_loss_full
    patience: 1000
  validation_logging:
    plot_path: ./plots/
data:
  batch_size: 16
  equation: ns
  file_path_test_x: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/harmonics_ldc_test_x.npz
  file_path_test_y: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/harmonics_ldc_test_y.npz
  file_path_train_x: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/harmonics_ldc_train_x.npz
  file_path_train_y: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/harmonics_ldc_train_y.npz
  inputs: sdf
  shuffle: true
  subsample: false
  train_split: 0.8
  type: collocation
  val_split: 0.2
model:
  branch_net_layers:
  - 512
  - 512
  - 512
  input_channels_func: 2
  input_channels_loc: 2
  log_file: log_pod-deeponet_lr=0.001_batch=5.txt
  lr: 0.0001
  modes: 64
  out_channels: 3
  output_channels: 5
  plot_path: ./plots/
  v_file: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/POD_data/pod_v_output_nurbs.npz
  y_mean_file: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/POD_data/pod_ymean_output_nurbs.npz
sweep_parameters:
  seed:
    values:
    - 0
    - 10
    - 20
trainer:
  accelerator: gpu
  devices: 1
  log_every_n_steps: 10
  max_epochs: 2
  seed: 0
