callbacks:
  checkpoint:
    dirpath: ./checkpoints/
    every_n_epochs: 5
    filename: poseidon-L-{epoch:02d}-{val_loss:.6f}
    mode: min
    monitor: val_loss_full
    save_top_k: -1
  early_stopping:
    monitor: val_loss_full
    patience: 1000
  validation_logging:
    plot_path: ./plots/
data:
  batch_size: 16
  equation: multiphase_bubble
  file_path: /work/mech-ai/mehdish/MPF-bench/RawData/2D/bubble/dataset
  train_split: 0.8
  type: field
  val_split: 0.2
model:
  depths:
  - 8
  - 8
  - 8
  - 8
  embed_dim: 192
  image_size: 256
  in_channels: 8
  log_file: log_poseidonL_test.txt
  lr: 5.0e-05
  out_channels: 4
  plot_path: ../plots/poseidon-L/nurbs/easy
  pretrained_path: camlab-ethz/Poseidon-L
sweep_parameters:
  seed:
    values:
    - 0
trainer:
  accelerator: gpu
  devices: 3
  log_every_n_steps: 10
  max_epochs: 10
  seed: 0
