callbacks:
  checkpoint:
    dirpath: ./checkpoints/
    every_n_epochs: 100
    filename: cno-{epoch:02d}-{val_loss:.6f}
    mode: min
    monitor: val_loss_full
    save_top_k: -1
  dirpath: ./checkpoints/
  early_stopping:
    monitor: val_loss_full
    patience: 1000
  validation_logging:
    plot_path: ./plots/
data:
  batch_size: 32
  equation: ns
  file_path_train_x: /work/mech-ai/rtali/projects/calderon_neural_operators/flowbench-sciml/data/train_capacitance_tensor3d_v2.npy
  file_path_train_y: /work/mech-ai/rtali/projects/calderon_neural_operators/flowbench-sciml/data/train_volume_tensor3d_v2.npy
  file_path_test_x: /work/mech-ai/rtali/projects/calderon_neural_operators/flowbench-sciml/data/test_capacitance_tensor3d_v2.npy
  file_path_test_y: /work/mech-ai/rtali/projects/calderon_neural_operators/flowbench-sciml/data/test_volume_tensor3d_v2.npy
  inputs: sdf
  shuffle: true
  subsample: false
  train_split: 0.8
  type: field
  val_split: 0.2
model:
  N_res: 6
  in_channels: 1
  in_size: 128
  log_file: log_cno_lr=0.001_batch=5.txt
  lr: 0.001
  n_layers: 4
  out_channels: 1
  out_size: 128
  plot_path: ./plots/
sweep_parameters:
  seed:
    values:
    - 91
trainer:
  accelerator: gpu
  devices: 1
  log_every_n_steps: 10
  max_epochs: 30
  seed: 91
