callbacks:
  checkpoint:
    dirpath: ./checkpoints/
    filename: cno-{epoch:02d}-{val_loss:.6f}
    mode: min
    monitor: val_loss_full
    save_top_k: 1
  early_stopping:
    monitor: val_loss_full
    patience: 1000
  validation_logging:
    plot_path: ./plots/
data:
  batch_size: 16
  equation: ns+ht
  file_path_test_x: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/nurbs_ldc_test_x.npz
  file_path_test_y: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/nurbs_ldc_test_y.npz
  file_path_train_x: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/nurbs_ldc_train_x.npz
  file_path_train_y: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/nurbs_ldc_train_y.npz
  inputs: sdf
  shuffle: true
  subsample: false
  train_split: 0.8
  type: field
  val_split: 0.2
model:
  N_res: 6
  in_channels: 3
  in_size: 512
  log_file: log_cno_lr=0.001_batch=5.txt
  lr: 0.001
  n_layers: 4
  out_channels: 4
  out_size: 512
  plot_path: ../plots/cno/nurbs/easy
sweep_parameters:
  seed:
    values:
    - 0
trainer:
  accelerator: gpu
  devices: 1
  log_every_n_steps: 10
  max_epochs: 400
  seed: 0
