callbacks:
  checkpoint:
    dirpath: ./checkpoints/
    every_n_epochs: 100
    filename: fno-{epoch:02d}
    mode: min
    monitor: val_loss_full
    save_top_k: -1
  dirpath: ./checkpoints/
  early_stopping:
    monitor: val_loss_full
    patience: 1000
  validation_logging:
    plot_path: ./plots/
data:
  batch_size: 100
  equation: ns
  file_path_train_x: /work/mech-ai/rtali/projects/calderon_neural_operators/flowbench-sciml/data/train_capacitance_tensor3d_v2.npy
  file_path_train_y: /work/mech-ai/rtali/projects/calderon_neural_operators/flowbench-sciml/data/train_param_tensor3d_v2.npy
  file_path_test_x: /work/mech-ai/rtali/projects/calderon_neural_operators/flowbench-sciml/data/test_capacitance_tensor3d_v2.npy
  file_path_test_y: /work/mech-ai/rtali/projects/calderon_neural_operators/flowbench-sciml/data/test_param_tensor3d_v2.npy
  inputs: sdf
  shuffle: true
  subsample: false
  train_split: 0.02
  type: field
  val_split: 0.01
model:
  hidden_channels: 4
  in_channels: 1
  log_file: log_fno_lr=0.001_batch=3.txt
  lr: 0.001
  n_layers: 6
  n_modes:
  - 8
  - 8
  out_channels: 8
  plot_path: ./plots/
  projection_channels: 4
sweep_parameters:
  seed:
    values:
    - 55
trainer:
  accelerator: gpu
  devices: 1
  log_every_n_steps: 10
  max_epochs: 150
  seed: 55
