callbacks:
  checkpoint:
    dirpath: ./checkpoints/all/easy
    filename: fno-{epoch:02d}
    mode: min
    monitor: val_loss_full
    save_top_k: 1
  early_stopping:
    monitor: val_loss_full
    patience: 1000
  validation_logging:
    plot_path: ./plots/
data:
  batch_size: 16
  equation: ns
  file_path_test_x: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/all_ldc_test_x.npz
  file_path_test_y: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/all_ldc_test_y.npz
  file_path_train_x: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/all_ldc_train_x.npz
  file_path_train_y: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NS_2D/processed/easy/all_ldc_train_y.npz
  inputs: sdf
  shuffle: true
  subsample: false
  train_split: 0.8
  type: field
  val_split: 0.2
model:
  hidden_channels: 16
  in_channels: 2
  log_file: log_fno_lr=0.001_batch=3.txt
  lr: 0.0001
  n_layers: 10
  n_modes:
  - 64
  - 64
  out_channels: 3
  plot_path: plots/fno/all/easy
  projection_channels: 16
sweep_parameters:
  seed:
    values:
    - 0
trainer:
  accelerator: gpu
  devices: 1
  log_every_n_steps: 10
  max_epochs: 200
  seed: 0
