callbacks:
  checkpoint:
    dirpath: ./checkpoints/skelneton/hard
    filename: poseidon-B-{epoch:02d}
    mode: min
    monitor: val_loss_full
    save_top_k: -1
    every_n_epochs: 100
  early_stopping:
    monitor: val_loss_full
    patience: 1000
  validation_logging:
    plot_path: ./plots/
data:
  batch_size: 8
  equation: ns+ht
  file_path_test_x: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NSHT_2D/processed/hard/skelneton_ldc_test_x.npz
  file_path_test_y: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NSHT_2D/processed/hard/skelneton_ldc_test_y.npz
  file_path_train_x: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NSHT_2D/processed/hard/skelneton_ldc_train_x.npz
  file_path_train_y: /work/mech-ai-scratch/arabeh/data_prep_ns/LDC_NSHT_2D/processed/hard/skelneton_ldc_train_y.npz
  inputs: sdf
  shuffle: true
  subsample: false
  train_split: 0.8
  type: field
  val_split: 0.2
model:
  depths:
  - 8
  - 8
  - 8
  - 8
  embed_dim: 96
  in_channels: 2
  log_file: log_poseidon-B_test.txt
  lr: 0.001
  out_channels: 3
  plot_path: plots/poseidon-B/skelneton/hard
  pretrained_path: camlab-ethz/Poseidon-B
sweep_parameters:
  seed:
    values:
    - 0
trainer:
  accelerator: gpu
  devices: 1
  log_every_n_steps: 10
  max_epochs: 200
  seed: 0
